services:
  core-router:
    image: debian:12
    container_name: core-router
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c "apt-get update &&
      apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold frr frr-pythontools iproute2 iputils-ping tcpdump &&
      sed -i 's/bgpd=no/bgpd=yes/' /etc/frr/daemons &&
      sed -i 's/ospfd=no/ospfd=yes/' /etc/frr/daemons &&
      /usr/lib/frr/frrinit.sh start || echo 'FRR failed to start, check logs' ;
      tail -f /dev/null"
    volumes:
      - ./frr/frr.conf:/etc/frr/frr.conf
    networks:
      net_core:
        ipv4_address: 120.0.31.2
      net_dmz:
        ipv4_address: 120.0.24.2
      net_ent_main:
        ipv4_address: 120.0.28.2
      net_ent_secondary:
        ipv4_address: 120.0.30.2
      net_box:
        ipv4_address: 120.0.16.2
      net_inter_as:
        ipv4_address: 200.0.0.2
  dmz-router:
    image: debian:12
    container_name: dmz-router
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c "apt-get update &&
      apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold frr frr-pythontools iproute2 iputils-ping tcpdump &&
      sed -i 's/bgpd=no/bgpd=yes/' /etc/frr/daemons &&
      sed -i 's/ospfd=no/ospfd=yes/' /etc/frr/daemons &&
      /usr/lib/frr/frrinit.sh start || echo 'FRR failed to start, check logs' ;
      tail -f /dev/null"
    volumes:
      - ./frr/dmz_frr.conf:/etc/frr/frr.conf
    networks:
      net_core:
        ipv4_address: 120.0.31.3
      net_dmz:
        ipv4_address: 120.0.24.3


networks:
  net_core:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.31.0/24

  net_dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.24.0/22

  net_ent_main:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.28.0/23

  net_ent_secondary:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.30.0/24

  net_box:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.16.0/21

  net_inter_as:
    driver: bridge
    ipam:
      config:
        - subnet: 200.0.0.0/29
