frr defaults traditional
hostname asn-router
service integrated-vtysh-config
log stdout

!
interface eth0
 description net_inter_as
 ip address 200.0.0.3/29
!
interface lo
 ip address 203.0.113.1/24
!
router bgp 65002
 bgp router-id 2.2.2.2
 neighbor 200.0.0.2 remote-as 65001
 !
 address-family ipv4 unicast
  network 203.0.113.0/24
  neighbor 200.0.0.2 activate
 exit-address-family
!
line vty
!
