frr defaults traditional
hostname box-router
service integrated-vtysh-config
log stdout

!
interface eth0
 description net_box
 ip address 120.0.16.3/21
!

router ospf
 ospf router-id 4.4.4.4
 network 120.0.16.0/21 area 0
!

line vty
!
