frr defaults traditional
hostname dmz-router
service integrated-vtysh-config
log stdout

!
interface eth0
 description net_core
 ip address 120.0.31.3/24
!
interface eth1
 description net_dmz
 ip address 120.0.24.3/22
!
router ospf
 ospf router-id 2.2.2.2
 network 120.0.31.0/24 area 0
 network 120.0.24.0/22 area 0
!
line vty
!
