frr defaults traditional
hostname ent-router
service integrated-vtysh-config
log stdout

!
interface eth0
 description net_core
 ip address 120.0.31.4/24
!
interface eth1
 description net_ent_main
 ip address 120.0.28.3/23
!
router ospf
 ospf router-id 3.3.3.3
 network 120.0.31.0/24 area 0
 network 120.0.28.0/23 area 0
!
line vty
!
