frr defaults traditional
hostname core-router
service integrated-vtysh-config
log stdout

!
! Interfaces (ordre = ordre des networks dans le compose)
!
interface eth0
 description net_core
 ip address 120.0.31.2/24
!
interface eth1
 description net_dmz
 ip address 120.0.24.2/22
!
interface eth2
 description net_ent_main
 ip address 120.0.28.2/23
!
interface eth3
 description net_ent_secondary
 ip address 120.0.30.2/24
!
interface eth4
 description net_box
 ip address 120.0.16.2/21
!
interface eth5
 description net_inter_as
 ip address 200.0.0.2/29
!
router ospf
 ospf router-id 1.1.1.1
 network 120.0.31.0/24 area 0
 network 120.0.24.0/22 area 0
 network 120.0.28.0/23 area 0
 network 120.0.30.0/24 area 0
 network 120.0.16.0/21 area 0
!
router bgp 65001
 bgp router-id 1.1.1.1
 neighbor 200.0.0.3 remote-as 65002
 !
 address-family ipv4 unicast
  network 120.0.16.0/21
  network 120.0.24.0/22
  network 120.0.28.0/23
  network 120.0.30.0/24
  network 120.0.31.0/24
  neighbor 200.0.0.3 activate
 exit-address-family
!
line vty
!

